// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfu0xB1w15TIYkO1ojPfrnLRXKVxVeF4',
    appId: '1:366558462632:web:b7af77e81897e96dd7f89d',
    messagingSenderId: '366558462632',
    projectId: 'flikker-5e864',
    authDomain: 'flikker-5e864.firebaseapp.com',
    storageBucket: 'flikker-5e864.appspot.com',
    measurementId: 'G-JWX6M9YEWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRv0LWjQAU0CF31tgyGhgPjspp6Ep6WpM',
    appId: '1:366558462632:android:96b81ef3734e2c6bd7f89d',
    messagingSenderId: '366558462632',
    projectId: 'flikker-5e864',
    storageBucket: 'flikker-5e864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7kBBs5pAnp4HUwkrP5DJRCDZJ91w5qY',
    appId: '1:366558462632:ios:9659a1ea145a6356d7f89d',
    messagingSenderId: '366558462632',
    projectId: 'flikker-5e864',
    storageBucket: 'flikker-5e864.appspot.com',
    iosClientId: '366558462632-9u2eaqkkb241trdq2f6b8j3bso9k2gpg.apps.googleusercontent.com',
    iosBundleId: 'com.app.flikker',
  );
}
